kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:latest
        ports:
          - name: client
            containerPort: 2181
            protocol: TCP
          - name: follower
            containerPort: 2888
            protocol: TCP
          - name: election
            containerPort: 3888
            protocol: TCP
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: 'yes'
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
          - name: kafka-client
            containerPort: 9092
            protocol: TCP
          - name: kafka-internal
            containerPort: 9093
            protocol: TCP
          - name: kafka-external
            containerPort: 9094
            protocol: TCP
        env:
        - name: KAFKA_ZOOKEEPER_PROTOCOL
          value: PLAINTEXT
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: 'yes'
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_CFG_LISTENERS
          value: INTERNAL://:9093,CLIENT://:9092,EXTERNAL://:9094
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: INTERNAL://kafka:9093,CLIENT://kafka:9092,EXTERNAL://localhost:9094
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
