apiVersion: v1
kind: Service
metadata:
  name: kafka-0-external
  namespace: default
  uid: 7d5f4e9a-b21c-406b-9655-00bd773253cc
  resourceVersion: '3204'
  creationTimestamp: '2022-11-15T16:21:09Z'
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-19.0.1
    pod: kafka-0
  annotations:
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: default
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      time: '2022-11-15T16:21:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
            f:pod: {}
        f:spec:
          f:allocateLoadBalancerNodePorts: {}
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":9094,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
  selfLink: /api/v1/namespaces/default/services/kafka-0-external
status:
  loadBalancer: {}
spec:
  ports:
    - name: tcp-kafka
      protocol: TCP
      port: 9094
      targetPort: kafka-external
      nodePort: 31467
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
    statefulset.kubernetes.io/pod-name: kafka-0
  clusterIP: 10.102.29.56
  clusterIPs:
    - 10.102.29.56
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster

