apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
  namespace: default
  uid: 6638bf18-13ec-485e-8e0e-18d88a5f699b
  resourceVersion: '3199'
  creationTimestamp: '2022-11-15T16:21:09Z'
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    helm.sh/chart: zookeeper-10.2.2
  annotations:
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: default
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      time: '2022-11-15T16:21:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":2181,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":2888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":3888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
  selfLink: /api/v1/namespaces/default/services/kafka-zookeeper
status:
  loadBalancer: {}
spec:
  ports:
    - name: tcp-client
      protocol: TCP
      port: 2181
      targetPort: client
    - name: tcp-follower
      protocol: TCP
      port: 2888
      targetPort: follower
    - name: tcp-election
      protocol: TCP
      port: 3888
      targetPort: election
  selector:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: zookeeper
  clusterIP: 10.104.213.139
  clusterIPs:
    - 10.104.213.139
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

