kafka:
  persistence:
    enabled: false
  zookeeper:
    persistence:
      enabled: false
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: true

  rbac:
    create: true

kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: kafka-dev
          bootstrapServers: kafka:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
